pipeline {
    agent any
    stages {
        stage('Prepare the environment'){
            steps {
                sh '''
                sudo chmod u+x ${WORKSPACE}/Scripts/script/prepare.sh
                sudo ${WORKSPACE}/Scripts/script/prepare.sh
                '''
            }
        }
        stage('Build the environment'){
            steps {
                sh '''
                sudo chmod u+x ${WORKSPACE}/Scripts/script/build.sh 
                sudo ${WORKSPACE}/Scripts/script/build.sh ${WORKSPACE}
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh '''
                sudo chmod u+x ${WORKSPACE}/Scripts/script/deploy.sh
                sudo ${WORKSPACE}/Scripts/script/deploy.sh ${WORKSPACE}
                '''
            }
        }
        stage('Sync') {
            steps {
                sh '''
                sudo chmod u+x ${WORKSPACE}/Scripts/script/sync.sh
                sudo ${WORKSPACE}/Scripts/script/sync.sh ${WORKSPACE}
                '''
            }
        }
    }
    post {
        always {
            cleanWs()
        }
     
    }
}
